# See the dedicated "version" documentation section.
version: "2"
linters:
  # Default: standard
  default: fast
  # Enable specific linter.
  enable:
    - errcheck
    - govet
    - unused
    - bodyclose
    - staticcheck
    - ineffassign
    - iface
    - ireturn
    - mnd
    - nilnil
    - wsl
  disable:
    - depguard
formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
issues:
  # See the dedicated "issues" documentation section.
  option: value
# Output configuration options.
output:
  # See the dedicated "output" documentation section.
  option: value
# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  option: value
severity:
  # See the dedicated "severity" documentation section.
  option: value